[package]
name = "test-crate-huayun"
version = "0.1.0"
edition = "2021"
license = "MIT"
authors = ["huayun zhang<huayun321@gmail.com>"]
description = "test publish"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
